### PR TITLE
replace static manifest and resource file with cmake macros

### PR DESCRIPTION
**Pull request by Jan200101**
creates a manifest and resource at configuration time and compiles them into the program.

Allows plugin creators to change to have multiple plugins in one project without having to manually manage resource definitions.

Checks which compiler and linker flags can be run by the compiler and adds them accordingly, useful to add MSVC support (though none has been added yet).

Resource file can be modified per plugin to give plugin specific information (name, version, etc.) but that is not implemented yet.

Plugins hip with a default manifest that has an empty description, version 0, run_on_{server,client} set to false and api_version set to 2.
On configuration the manifest name is set to the target name and the version to the project version to fall back on existing information, but those can be specified using `plugin_manifest`

### CODE REVIEW

**Comment by uniboi** [comment]
Works in testing but this generates a folder for every plugin I assume that isn't ignored by git.
image
Maybe make a ``manifest`` folder where you generate the folders into and add it to .gitignore

**Comment by Jan200101** [comment]
This has been mentioned on Discord already
the folder is only generated in the build folder, in-tree builds are highly discouraged with cmake

**Comment by F1F7Y** [comment]
> This has been mentioned on Discord already the folder is only generated in the build folder, in-tree builds are highly discouraged with cmake

Considering the Readme doesnt mention this and most people dont know cmake maybe we should default to something like:
```
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build)
```

**Comment by Jan200101** [comment]
> > This has been mentioned on Discord already the folder is only generated in the build folder, in-tree builds are highly discouraged with cmake
> 
> Considering the Readme doesnt mention this and most people dont know cmake maybe we should default to something like:
> 
> ```
> set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build)
> ```

that wouldn't fix anything

a check could be added to see if CMAKE_BINARY_DIR and CMAKE_SOURCE_DIR are the same to yell at the user.

**Pull request merged**
